name: Trigger auto deployment for dockerappcont

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/dockerappcont-AutoDeployTrigger-096b4ea8-55c7-41d5-a43c-c40be64fc805.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DOCKERAPPCONT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DOCKERAPPCONT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DOCKERAPPCONT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.DOCKERAPPCONT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DOCKERAPPCONT_REGISTRY_PASSWORD }}
          containerAppName: dockerappcont
          resourceGroup: contapresources
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


